apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner
  namespace: gitlab
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner
  namespace: gitlab 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner 
subjects:
- namespace: gitlab
  kind: ServiceAccount
  name: runner 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: gitlab 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner 
subjects:
- namespace: gitlab
  kind: ServiceAccount
  name: default 
